const StaticVariables = {
  EMPTY_STRING: '',
  EMPTY_ARRAY: [] as any[],
  EMPTY_OBJECT: {},
  WelcomeScreen: 'WelcomeScreen',
  PreferenceScreen: 'PreferenceScreen',
  RegisterScreen1: 'RegisterScreen1',
  RegisterScreen2: 'RegisterScreen2',
  SignInScreen: 'SignInScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  ChangePasswordScreen: 'ChangePasswordScreen',
  HomeStack: 'HomeStack',
  HomeScreen: 'HomeScreen',
  ProfileScreen: 'ProfileScreen',
  EditZipcodeScreen: 'EditZipcodeScreen',
  HotelScreen: 'HotelScreen',
  ReviewsScreen: 'ReviewsScreen',
  AddReviewScreen: 'AddReviewScreen',
  MenuScreen: 'MenuScreen',
  FoodItemScreen: 'FoodItemScreen',
  OrderStack: 'OrderStack',
  OrderScreen: 'OrderScreen',
  VehicleScreen: 'VehicleScreen',
  AddressScreen: 'AddressScreen',
  PaymentInfoScreen: 'PaymentInfoScreen',
  SummaryScreen: 'SummaryScreen',
  SuccessScreenDineIn: 'SuccessScreenDineIn',
  SuccessScreenCarryOut: 'SuccessScreenCarryOut',
  SuccessScreenDelivery: 'SuccessScreenDelivery',
  TrackingScreen: 'TrackingScreen',
  ContactUsScreen: 'ContactUsScreen',
};
export default StaticVariables;
