const StaticVariables = {
  ADMIN_UID: 'we6tn0gQieW6MnYxywoohjNhsP63',
  ADMIN_Email: 'admin@gmail.com',
  EMPTY_STRING: '',
  EMPTY_ARRAY: [] as any[],
  EMPTY_OBJECT: {},
  WelcomeScreen: 'WelcomeScreen',
  PreferenceScreen: 'PreferenceScreen',
  RegisterScreen1: 'RegisterScreen1',
  RegisterScreen2: 'RegisterScreen2',
  SignInScreen: 'SignInScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  ChangePasswordScreen: 'ChangePasswordScreen',
  HomeStack: 'HomeStack',
  HomeScreen: 'HomeScreen',
  ProfileScreen: 'ProfileScreen',
  EditZipcodeScreen: 'EditZipcodeScreen',
  HotelScreen: 'HotelScreen',
  MenuScreen: 'MenuScreen',
  FoodItemScreen: 'FoodItemScreen',
  OrderScreen: 'OrderScreen',
  VehicleScreen: 'VehicleScreen',
  AddressScreen: 'AddressScreen',
  PaymentInfoScreen: 'PaymentInfoScreen',
  SummaryScreen: 'SummaryScreen',
  SuccessScreenDineIn: 'SuccessScreenDineIn',
  SuccessScreenCarryOut: 'SuccessScreenCarryOut',
  SuccessScreenDelivery: 'SuccessScreenDelivery',
  TrackingScreen: 'TrackingScreen',
  ContactUsScreen: 'ContactUsScreen',
};
export default StaticVariables;
